// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL bypasses Supabase's PgBouncer pooler (port 6543) so that
    // DDL statements in migrations work correctly. Use the direct connection
    // string (port 5432) from your Supabase project settings here.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
